
CREATE TABLE receipts (
  id INT UNSIGNED AUTO_INCREMENT,
  uploaded DATETIME DEFAULT CURRENT_TIMESTAMP(),
  merchant VARCHAR(255),
  amount DECIMAL(12,2),
  tag VARCHAR(255),
  receipt_type INT UNSIGNED,
  image LONGVARCHAR(MAX),

  PRIMARY KEY (id)
);